### ISSUE TITLE
Claiming

### ISSUE THREAD

**Issue by Richienb** [Richienb/get-client-xy#2]
I'd like to claim this package.

My npm username is `richienb`.

**Comment by dy** [comment]
Can you briefly describe your plans? That package is a dependency of 3 others, need some guarantees

**Comment by Richienb** [comment]
I'm going to refactor it and incorporate #1.

**Comment by dy** [comment]
Transfered. Please don't release the breaking PR #1 as minor, it is major

**Comment by Richienb** [comment]
👍

**Comment by dy** [comment]
Also please add me as a contributor.

**Comment by Richienb** [comment]
Do you mean collaborator?

**Comment by dy** [comment]
Yes, to have access to the repository settings.

**Comment by dy** [comment]
Added you as owner of npm https://www.npmjs.com/package/get-client-xy

<blockquote><img src="https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png" width="48" align="right"><div><img src="https://static.npmjs.com/da3ab40fb0861d15c83854c29f5f2962.png" height="14"> npm</div><div><strong><a href="https://www.npmjs.com/package/get-client-xy">get-client-xy</a></strong></div><div>Get clientX/clientY from an event</div></blockquote>

**Comment by Richienb** [comment]
Already added

![image](https://user-images.githubusercontent.com/29491356/103482052-5faed200-4e43-11eb-9fab-c6cb0097e5d8.png)

**Comment by Richienb** [comment]
@dy Since almost all use cases of this package obtain the x and y coordinates at the same time, can we merge them into the same function?

**Comment by dy** [comment]
Yes, totally reasonable. It’s just breaking change, must be bumped major.
Also I would refactor to ES modules at once (no need for cjs fallback since
that’s browser-only pkg).

**Comment by dy** [comment]
I would also propose returning an array instead if object to make both work:
let [x, y] = clientxy(e)
let {x, y} = clientxy(e)
(second is not even necessary - it is just destructuring object is heavier than array)

**Comment by Richienb** [comment]
Released [`get-client-xy`](https://www.npmjs.com/package/get-client-xy) v2.0.0
